name: Gerar APK do Jarvis

on:
  push:
    branches:      # Isso avisa o GitHub para rodar o código em qualquer branch que você mexer!
      - main
      - principal
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do GitHub
        uses: actions/checkout@v4

      - name: Configurar o Python Estável
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configurar o Java (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar o Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependências e Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          pip install --upgrade pip
          pip install flet==0.21.2 google-generativeai

      - name: Gerar o APK com o Flet
        run: |
         yes | sdkmanager --licenses
         flet build apk
  
        
          
      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Gerar APK do Jarvis

on:
  push:
    branches:
      - main
      - principal
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do GitHub
        uses: actions/checkout@v4

      - name: Configurar o Python Estável
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configurar o Java (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar o Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependências e Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          pip install --upgrade pip
          pip install flet==0.21.2 google-generativeai

      - name: Gerar o APK com o Flet
        run: |
          flet build apk --no-interactive
          
      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: build/apk/*.apk
          
